### PR TITLE
Add API changes from the Aegis Sovereignty patch.

### PR DESCRIPTION
**Pull request by ayust**
Bookmark endpoints, contact labels, and positions for stations.

### CODE REVIEW

**Comment by ayust** [comment]
Note: don't merge this until tomorrow; it relies on things not yet pushed to Tranquility.

**Comment by damienb** [comment]
Should the station coords be floats or ints?

**Comment by ayust** [comment]
Location values are floats. Stations generally happen to be on integer values, but we shouldn't assume that (hence the .0 I added in the test data).

**Comment by damienb** [comment]
Makes sense. SGTM

**Pull request merged**
